#!/bin/bash

(

cd postProcessing/collapsedFields;

ls | grep '[0-9]\+$' | sort -n | tail -n1 | while read n;do cp -r "$n" latesTimeDir;done

cd latesTimeDir;

join p0Mean.xy pSigmaMean.xy 					> tmp; mv tmp pMean.xy;

join U0Mean_X.xy USigmaMean_X.xy 				> tmp; mv tmp UMean_X.xy;
join U0Prime2Mean_XX.xy USigmaPrime2Mean_XX.xy 	> tmp; mv tmp UPrime2Mean_XX.xy;
join U0Prime2Mean_YY.xy USigmaPrime2Mean_YY.xy 	> tmp; mv tmp UPrime2Mean_YY.xy;
join U0Prime2Mean_ZZ.xy USigmaPrime2Mean_ZZ.xy 	> tmp; mv tmp UPrime2Mean_ZZ.xy;
join U0Prime2Mean_XY.xy USigmaPrime2Mean_XY.xy 	> tmp; mv tmp UPrime2Mean_XY.xy;

)

